language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t samu126/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true samu126/docker-react npm run test

deploy:
    provided: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-635618490012"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY